---
- name: Install docker
  apk:
    name:
      - docker
      - docker-compose
    state: present

- name: Add cgroups to default runlevel
  command: rc-update add cgroups default
  args:
    creates: /etc/runlevels/default/cgroups

- name: Ensure cgroups is started
  service:
    name: cgroups
    state: started
    enabled: yes

- name: Add docker to default runlevel
  command: rc-update add docker default
  args:
    creates: /etc/runlevels/default/docker

- name: Ensure docker is started
  service:
    name: docker
    state: started
    enabled: yes
