---
- name: Install security packages
  apk:
    name:
      - doas
      - sudo
    state: present

- name: Configure sudo
  copy:
    src: sudoers.d/custom
    dest: /etc/sudoers.d/custom
    owner: root
    group: root 
    mode: 0600
