---
- name: Add custom openSSH configuration
  copy:
    src: ssh/custom.conf
    dest: /etc/ssh/sshd_config.d/custom.conf
    owner: root
    group: wheel
    mode: 0600
  tags: ['ssh']

- name: Add AllowUsers configuration
  copy:
    dest: /etc/ssh/sshd_config.d/users.conf
    content: |
      AllowUsers root {{ target_user }}
    owner: root
    group: root
    mode: '0600'
  tags: ['ssh']
