---
- name: Add shell & man
  apk:
    name:
      - bash
      - bash-completion
      - man-pages
      - mandoc
    state: present
  tags: ['apk', 'user']

- name: Add user to needed groups
  user:
    name: "{{ target_user }}"
    groups: wheel,plugdev
    append: yes
    shell: /bin/bash
  tags: ['user']

- name: Fix HOME permissions
  file:
    path: "/home/{{ target_user }}"
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '6750'
  tags: ['user']
